// All site content lives here. Edit text in this file, then run `node build.js`.

const BIZ = {
  name: 'Ideal House',
  url: 'https://www.idealhouse.nl',
  phone: '06 34 71 49 09',
  tel: '+31634714909',
  email: 'idealhousenl@gmail.com',
  street: 'Schiekade 10B',
  zip: '3032 AJ',
  city: 'Rotterdam',
  region: 'Zuid-Holland',
  owner: 'O.I.U. Pulatkhonov',
  kvk: '42060424',
  btw: 'NL005465387896',
  lat: 51.9296,
  lng: 4.4741,
  wa: 'https://wa.me/31634714909',
  maps: 'https://www.google.com/maps/search/?api=1&query=Ideal+House+Schiekade+10B+3032+AJ+Rotterdam',
  hours: [
    ['Maandag – vrijdag', '08:00 – 18:00'],
    ['Zaterdag', '09:00 – 16:00'],
    ['Zondag', 'Gesloten'],
  ],
};

const waLink = (topic) =>
  BIZ.wa + '?text=' + encodeURIComponent(`Hallo Ideal House, ik heb een vraag over ${topic || 'een verbouwing'}.`);

const CITIES = ['Rotterdam', 'Schiedam', 'Vlaardingen', 'Capelle aan den IJssel', 'Barendrecht', 'Ridderkerk',
  'Spijkenisse', 'Delft', 'Den Haag', 'Dordrecht', 'Zoetermeer', 'Gouda'];

const DISTRICTS = ['Kralingen', 'Hillegersberg', 'Blijdorp', 'Rotterdam-Noord', 'Crooswijk', 'Delfshaven',
  'Overschie', 'Prins Alexander', 'Feijenoord', 'Charlois', 'IJsselmonde', 'Hoogvliet'];

const SERVICES = [
  {
    slug: 'badkamerrenovatie',
    name: 'Badkamer- & toiletrenovatie',
    short: 'badkamerrenovatie',
    icon: 'bath',
    card: 'Van ontwerp tot de laatste kitrand: een complete badkamer, sleutelklaar opgeleverd.',
    tags: ['Inloopdouche', 'Toilet', 'Sanitair'],
    title: 'Badkamer renoveren in Rotterdam | Ideal House',
    desc: 'Badkamer of toilet laten renoveren in Rotterdam? Ideal House regelt sloop, leidingwerk, elektra, tegelwerk en montage. Eén aanspreekpunt, vaste prijs vooraf. Gratis offerte.',
    h1: 'Badkamerrenovatie in Rotterdam, sleutelklaar opgeleverd',
    intro: 'Een badkamer verbouwen raakt bijna elk vak: sloopwerk, riolering, waterleiding, elektra, tegelwerk, stucwerk en montage. Ideal House voert al die stappen zelf uit, in de juiste volgorde en met één planning. U hoeft dus niet zelf een loodgieter, tegelzetter en elektricien op elkaar af te stemmen.',
    hero: 'badkamer-inloopdouche-led-spiegel',
    gallery: ['badkamer-wastafelmeubel-ovale-spiegel', 'badkamer-dubbele-wastafel-nissen', 'toilet-groene-staaftegels', 'toilet-hangend-led-nis', 'badkamer-inloopdouche-led-spiegel'],
    includes: [
      'Compleet slopen en afvoeren van de oude badkamer',
      'Nieuwe waterleiding, riolering en afvoeren volgens de normen',
      'Elektra, verlichting, spiegelverwarming en wandcontactdozen',
      'Wand- en vloertegels, inclusief inloopdouche en douchegoot',
      'Waterdichte afdichting onder het tegelwerk met kimband en folie',
      'Montage van sanitair, meubel, kranen, radiator en glaswand',
    ],
    steps: [
      ['Opname op locatie', 'We meten de ruimte in, bespreken uw wensen en beoordelen de bestaande leidingen.'],
      ['Ontwerp en offerte', 'U ontvangt een indeling en een gespecificeerde offerte met een duidelijke prijs per onderdeel.'],
      ['Uitvoering', 'Sloop, installatie, tegelwerk en montage. Doorgaans binnen 10 tot 15 werkdagen.'],
      ['Oplevering', 'We lopen de badkamer samen na, ruimen alles op en leveren schoon op.'],
    ],
    about: [
      'Een goede badkamer zie je aan de details: een douchevloer die precies naar de goot afloopt, tegels die strak in lijn liggen en kitranden zonder slordige overgangen. Maar het belangrijkste werk zit achter de tegels. Daarom besteden we veel aandacht aan de waterdichte laag, de leidingen en het afschot. Dat is wat ervoor zorgt dat uw badkamer jarenlang zonder lekkage of vocht blijft.',
      'Of u nu kiest voor een inloopdouche met glaswand, een ligbad, een hangend toilet of een wastafelmeubel met verlichte spiegel: we denken mee over een indeling die praktisch is in het dagelijks gebruik. Ook in kleine Rotterdamse badkamers en onder schuine zolderdaken halen we het maximale uit de ruimte.',
    ],
    faqs: [
      ['Wat kost een badkamerrenovatie?', 'Dat hangt af van de afmetingen, of leidingen verlegd moeten worden en welke tegels en welk sanitair u kiest. Na de opname op locatie ontvangt u een gespecificeerde offerte met een vaste prijs per onderdeel, zodat u precies weet waar u aan toe bent.'],
      ['Hoelang zit ik zonder badkamer?', 'Een complete badkamer duurt gemiddeld 10 tot 15 werkdagen. In de offerte noemen we een concrete doorlooptijd, zodat u vooraf een tijdelijke oplossing kunt regelen als dat nodig is.'],
      ['Kunnen jullie ook alleen het toilet vernieuwen?', 'Ja. Een toiletrenovatie voeren we ook als losse opdracht uit, inclusief inbouwreservoir, tegelwerk, fontein en verlichting. Omdat het een kleiner project is, is het ook sneller klaar.'],
    ],
  },
  {
    slug: 'aanbouw-en-uitbouw',
    name: 'Aanbouw & uitbouw',
    short: 'aanbouw of uitbouw',
    icon: 'extension',
    card: 'Meer ruimte zonder te verhuizen, van fundering tot dakbedekking en afwerking.',
    tags: ['Fundering', 'Schuifpui', 'Lichtstraat'],
    title: 'Aanbouw of uitbouw laten bouwen in Rotterdam | Ideal House',
    desc: 'Een aanbouw of uitbouw in Rotterdam en omgeving? Ideal House verzorgt fundering, metselwerk, staal, kozijnen, dak en complete afbouw. Advies over vergunningen. Gratis offerte.',
    h1: 'Aanbouw & uitbouw in Rotterdam: meer ruimte zonder te verhuizen',
    intro: 'Een uitbouw aan de achterzijde of een dakkapel levert vaak meer op dan een verhuizing. Ideal House verzorgt de volledige ruwbouw en afbouw: fundering, metselwerk, staalconstructie, kozijnen, dakbedekking en de complete binnenafwerking.',
    hero: 'serre-aanbouw-staal-glas',
    gallery: ['aanbouw-schuifpui-rotterdam', 'woonkeuken-lichtstraat-uitbouw', 'aanbouw-glazen-pui-tuinzijde', 'uitbouw-baksteen-stalen-deuren', 'aanbouw-houten-gevelbekleding', 'aanbouw-antraciet-gevelbekleding'],
    includes: [
      'Fundering en vloer, inclusief isolatie',
      'Metselwerk, lateien en staalconstructie',
      'Kozijnen, schuifpuien en dakramen',
      'Platdakbedekking en waterdichte aansluitingen',
      'Isolatie, wanden, plafonds en stucwerk',
      'Advies over vergunningvrij bouwen of de omgevingsvergunning',
    ],
    steps: [
      ['Haalbaarheid', 'We kijken naar de constructie, de erfgrens en of uw plan vergunningvrij kan.'],
      ['Tekening en offerte', 'Waar nodig schakelen we een constructeur in voor de berekening.'],
      ['Ruwbouw', 'Fundering, metselwerk, staal en dak. Het casco staat waterdicht.'],
      ['Afbouw', 'Isolatie, wanden, elektra, stucwerk en de vloerafwerking.'],
    ],
    about: [
      'Met een aanbouw of uitbouw maakt u van een krappe woonkamer een ruime, lichte leefkeuken. Denk aan een uitbouw met grote schuifpui naar de tuin, een lichtstraat die daglicht diep de woning in brengt of een serre met stalen kozijnen. Omdat wij zowel de ruwbouw als de afbouw zelf doen, sluit alles naadloos op elkaar aan.',
      'Veel uitbouwen aan de achterzijde zijn vergunningvrij, maar dat hangt af van de afmetingen en uw perceel. Tijdens de opname kijken we hiernaar. Is er wel een omgevingsvergunning nodig, dan helpen we u met de tekeningen en de aanvraag. Het meeste werk gebeurt buiten. Pas aan het eind maken we de doorbraak naar de bestaande woning, zodat u zo kort mogelijk overlast heeft.',
    ],
    story: true,
    faqs: [
      ['Heb ik een vergunning nodig voor een aanbouw?', 'Dat hangt af van de afmetingen en de locatie op het perceel. Veel uitbouwen aan de achterzijde zijn vergunningvrij. Tijdens de opname kijken we hiernaar en, als er wel een omgevingsvergunning nodig is, helpen we u met de aanvraag.'],
      ['Kan ik thuis blijven wonen tijdens de bouw?', 'In de meeste gevallen wel. De aanbouw wordt grotendeels aan de buitenkant gebouwd. Pas als het casco waterdicht staat, maken we de doorbraak naar de woning. We plaatsen stofschotten en ruimen elke dag op.'],
      ['Wie maakt de constructieberekening?', 'Waar nodig schakelen wij een constructeur in voor de berekening van fundering en staal. Die kosten nemen we op in de offerte, zodat u niet zelf partijen hoeft te zoeken.'],
    ],
  },
  {
    slug: 'schilderwerk',
    name: 'Schilderwerk binnen & buiten',
    short: 'schilderwerk',
    icon: 'roller',
    card: 'Strak sauswerk binnen en duurzaam onderhoudsschilderwerk buiten.',
    tags: ['Sauswerk', 'Kozijnen', 'Houtrot'],
    title: 'Schilder Rotterdam | Binnen & buiten | Ideal House',
    desc: 'Schilderwerk in Rotterdam: wanden en plafonds sauzen, lakwerk van deuren en kozijnen, buitenschilderwerk met houtrotherstel. Zorgvuldige voorbereiding, schoon opgeleverd.',
    h1: 'Schilderwerk binnen & buiten in Rotterdam',
    intro: 'Goed schilderwerk begint bij de voorbereiding. We schuren, plamuren en gronden zorgvuldig, zodat de afwerklaag hecht en jarenlang mooi blijft. Binnen werken we stofarm en dekken we uw vloer en meubels volledig af.',
    hero: 'strak-stucwerk-lichtstraat',
    gallery: ['strak-stucwerk-lichtstraat', 'woonkeuken-lichtstraat-uitbouw', 'aanbouw-antraciet-gevelbekleding', 'uitbouw-openslaande-tuindeuren'],
    includes: [
      'Wanden en plafonds sauzen, gespoten of gerold',
      'Lak- en schilderwerk van deuren, kozijnen en trappen',
      'Buitenschilderwerk inclusief houtrotherstel',
      'Behangwerk en glasweefsel',
      'Stuc- en spackwerk als ondergrond',
      'Kleuradvies en proefstalen vooraf',
    ],
    steps: [
      ['Inspectie', 'We beoordelen de ondergrond en eventueel houtrot of loszittende verf.'],
      ['Voorbereiden', 'Afplakken, schuren, plamuren en gronden. De basis voor een strak resultaat.'],
      ['Afwerken', 'Twee dekkende lagen in de door u gekozen kleur.'],
      ['Opruimen', 'We halen het afplakmateriaal weg en leveren de ruimte schoon op.'],
    ],
    about: [
      'Binnen zorgt strak sauswerk voor een rustige, frisse uitstraling. Na een verbouwing werken we wanden en plafonds af tot ze klaar zijn om in te wonen, zonder dat u nog een aparte schilder hoeft te zoeken. Deuren, kozijnen en trappen lakken we in een slijtvaste laklaag die tegen een stootje kan.',
      'Buiten beschermt goed schilderwerk uw kozijnen, boeidelen en gevelbekleding tegen weer en wind. We sporen houtrot op, herstellen het vakkundig en bouwen daarna een verfsysteem op dat lang meegaat. Zo voorkomt u dure reparaties in de toekomst.',
    ],
    faqs: [
      ['Wanneer is het beste moment voor buitenschilderwerk?', 'Buitenschilderwerk doen we bij droog weer en een temperatuur boven de 7 graden. In de praktijk is dat van het voorjaar tot in het vroege najaar. Binnenschilderwerk kan het hele jaar door.'],
      ['Hoe vaak moet buitenschilderwerk opnieuw?', 'Gemiddeld eens in de zes à acht jaar, afhankelijk van de ligging van de gevel en het verfsysteem. Tussentijds een keer bijwerken verlengt de levensduur flink.'],
      ['Helpen jullie bij het kiezen van een kleur?', 'Ja. We geven kleuradvies en zetten op verzoek proefstalen op de wand, zodat u de kleur in uw eigen licht kunt beoordelen voordat we beginnen.'],
    ],
  },
  {
    slug: 'tegelwerk-en-metselwerk',
    name: 'Tegel- & metselwerk',
    short: 'tegel- of metselwerk',
    icon: 'bricks',
    card: 'Strak uitgelijnd tegelwerk en vakkundig metselwerk, tot in de laatste voeg.',
    tags: ['Grootformaat', 'Visgraat', 'Gevelherstel'],
    title: 'Tegelzetter & metselaar Rotterdam | Ideal House',
    desc: 'Tegelzetter of metselaar nodig in Rotterdam? Grootformaat tegels, marmerlook, douchegoten op afschot, metselwerk en gevelherstel. Strak uitgelijnd tot in de laatste voeg.',
    h1: 'Tegelwerk & metselwerk in Rotterdam, tot in de laatste voeg',
    intro: 'Tegelwerk is precisiewerk: de ondergrond moet vlak zijn, het patroon moet uitkomen en het afschot naar de goot moet kloppen. Wij werken met nivelleersystemen en zetten grootformaat- en marmerlooktegels strak in het verband.',
    hero: 'badkamer-dubbele-wastafel-nissen',
    gallery: ['toilet-groene-staaftegels', 'badkamer-inloopdouche-led-spiegel', 'toilet-hangend-led-nis', 'uitbouw-baksteen-stalen-deuren', 'uitbouw-metselwerk-in-uitvoering', 'gevel-dakopbouw-metselwerk'],
    includes: [
      'Grootformaat wand- en vloertegels',
      'Marmerlook, natuursteen, keramiek en visgraatpatroon',
      'Egaliseren en waterdicht afdichten van de ondergrond',
      'Douchegoten en afschot op maat',
      'Metselwerk, voegwerk en herstel van gevels',
      'Schoorstenen, tuinmuren en dilatatievoegen',
    ],
    steps: [
      ['Ondergrond', 'Egaliseren, uitvlakken en waterdicht maken waar dat nodig is.'],
      ['Uitzetten', 'We bepalen het startpunt zodat snijranden op de minst zichtbare plek vallen.'],
      ['Tegelen', 'Zetten met nivelleerclips voor een vlak resultaat zonder hoogteverschillen.'],
      ['Voegen en kitten', 'Voegen in de gekozen kleur en sanitaire kit in alle hoeken.'],
    ],
    about: [
      'Bij tegelwerk zie je elk verschil van een millimeter. Daarom zetten we het patroon vooraf uit, zodat de snijranden op de minst zichtbare plek vallen en voegen netjes doorlopen van wand naar vloer. Met nivelleerclips liggen ook grote tegels van 60×120 cm of meer vlak en zonder randjes.',
      'Ons metselwerk varieert van een complete nieuwe uitbouw tot het herstellen van scheuren en het opnieuw voegen van een oude Rotterdamse gevel. We zoeken stenen en voegmortel die aansluiten bij het bestaande werk, zodat de reparatie niet opvalt.',
    ],
    faqs: [
      ['Kunnen jullie grootformaat tegels leggen?', 'Ja. We zetten grootformaat tegels met een nivelleersysteem, zodat ze vlak liggen zonder hoogteverschillen. Belangrijk daarbij is een goed geëgaliseerde ondergrond; die nemen we mee in de offerte.'],
      ['Mag ik de tegels zelf uitzoeken?', 'Zeker. Veel klanten kiezen zelf hun tegels bij een showroom. We adviseren graag over formaat, voegbreedte en hoeveelheid, of we verzorgen het complete pakket voor u.'],
      ['Herstellen jullie ook voegwerk van de gevel?', 'Ja. We hakken verweerde voegen uit, herstellen beschadigd metselwerk en voegen opnieuw in een kleur die past bij de rest van de gevel.'],
    ],
  },
  {
    slug: 'loodgieterswerk',
    name: 'Loodgieterswerk & vloerverwarming',
    short: 'loodgieterswerk',
    icon: 'drop',
    card: 'Waterleiding, riolering, cv en vloerverwarming, netjes weggewerkt en lekvrij.',
    tags: ['Riolering', 'Vloerverwarming', 'Cv'],
    title: 'Loodgieter & vloerverwarming Rotterdam | Ideal House',
    desc: 'Loodgieter in Rotterdam voor waterleiding, riolering, cv, radiatoren en vloerverwarming. Volgens de normen aangelegd en op druk getest. Vraag een gratis offerte aan.',
    h1: 'Loodgieterswerk & vloerverwarming in Rotterdam',
    intro: 'Van het vervangen van een verouderde rioolstreng in de kruipruimte tot het aanleggen van vloerverwarming in de woonkamer: we leggen leidingen volgens de geldende normen aan en testen alles op druk voordat het wordt dichtgemaakt.',
    hero: 'toilet-hangend-led-nis',
    gallery: ['badkamer-inloopdouche-led-spiegel', 'badkamer-wastafelmeubel-ovale-spiegel', 'toilet-groene-staaftegels', 'badkamer-dubbele-wastafel-nissen'],
    includes: [
      'Waterleiding vervangen of uitbreiden in meerlaags en koper',
      'Riolering en afvoeren, ook in de kruipruimte',
      'Vloerverwarming, ingefreesd of in een nieuwe dekvloer',
      'Cv-installatie, radiatoren en verdelers',
      'Lekkages opsporen en verhelpen',
      'Aansluiten van sanitair, keuken en wasmachine',
    ],
    steps: [
      ['Inventarisatie', 'We brengen de bestaande installatie in kaart en bepalen de route.'],
      ['Aanleg', 'Leidingen worden op de juiste afstand en met correct afschot gemonteerd.'],
      ['Afpersen', 'De installatie wordt onder druk getest voordat er iets wordt dichtgezet.'],
      ['Aansluiten', 'Sanitair en apparatuur worden aangesloten en in bedrijf gesteld.'],
    ],
    about: [
      'Leidingwerk zie je niet meer zodra de wand of vloer dicht is. Juist daarom moet het in één keer goed. We monteren leidingen met het juiste afschot en de juiste bevestiging, en persen de installatie af voordat er iets wordt weggewerkt. Zo weet u zeker dat alles lekvrij is.',
      'Vloerverwarming is comfortabel en zuinig, zeker in combinatie met een warmtepomp. In een bestaande dekvloer kunnen we de leidingen vaak infrezen, zonder dat de vloer omhoog hoeft. Bij een verbouwing of aanbouw leggen we de leidingen in de nieuwe dekvloer.',
    ],
    faqs: [
      ['Kan vloerverwarming in mijn bestaande vloer?', 'Vaak wel. Bij een cementdekvloer van voldoende dikte frezen we sleuven en leggen we de leidingen erin, zonder dat de vloer hoger wordt. Tijdens de opname beoordelen we of uw vloer geschikt is.'],
      ['Lossen jullie ook lekkages op?', 'Ja. We sporen de oorzaak van een lekkage op en verhelpen die, of het nu gaat om een leiding, een afvoer of een slechte aansluiting bij het sanitair.'],
      ['Mijn woning heeft nog oude leidingen. Moeten die vervangen worden?', 'In oudere woningen zitten soms nog loden of verouderde leidingen. Die raden we aan te vervangen door meerlaags of koperen leidingen, zeker als u toch gaat verbouwen. We bekijken de situatie en adviseren eerlijk.'],
    ],
  },
  {
    slug: 'elektra-en-keukenmontage',
    name: 'Elektra & keukenmontage',
    short: 'elektra of keukenmontage',
    icon: 'bolt',
    card: 'Groepenkast, bedrading en verlichting, plus uw keuken vakkundig gemonteerd.',
    tags: ['Groepenkast', 'Verlichting', 'Keuken'],
    title: 'Elektricien & keukenmontage in Rotterdam | Ideal House',
    desc: 'Elektricien in Rotterdam: groepenkast vervangen, herbedrading, spots en LED-verlichting volgens NEN 1010. Ook complete keukenmontage inclusief aansluiten van apparatuur.',
    h1: 'Elektra & keukenmontage in Rotterdam, veilig en netjes weggewerkt',
    intro: 'Elektrawerk voeren we uit volgens NEN 1010. Of het nu gaat om een paar extra groepen, nieuwe bedrading door de hele woning of het monteren en aansluiten van een keuken: het wordt veilig en netjes weggewerkt.',
    hero: 'woonkeuken-lichtstraat-uitbouw',
    gallery: ['woonkeuken-lichtstraat-uitbouw', 'badkamer-dubbele-wastafel-nissen', 'aanbouw-schuifpui-rotterdam', 'strak-stucwerk-lichtstraat'],
    includes: [
      'Groepenkast vervangen of uitbreiden',
      'Complete herbedrading van de woning',
      'Wandcontactdozen, schakelaars en data-aansluitingen',
      'Inbouwspots, LED-verlichting en dimmers',
      'Keukenmontage inclusief werkblad en apparatuur',
      'Aansluiten van kookplaat, oven, afzuigkap en vaatwasser',
    ],
    steps: [
      ['Plan', 'We bepalen samen waar u stopcontacten, schakelaars en verlichting wilt.'],
      ['Hak- en freeswerk', 'Leidingen gaan in de wand, zodat er niets zichtbaar blijft.'],
      ['Bedraden', 'Trekken van de kabels en aansluiten op de groepenkast.'],
      ['Testen', 'Alle groepen worden gemeten en getest voor gebruik.'],
    ],
    about: [
      'Een moderne woning vraagt meer van de elektrische installatie dan vroeger: een inductiekookplaat, een warmtepomp, een laadpaal of zonnepanelen. Met een goed ingedeelde groepenkast en voldoende aardlekbeveiliging is uw woning daar klaar voor. We adviseren wat nodig is, en wat niet.',
      'Een nieuwe keuken monteren we compleet: kasten waterpas stellen, werkblad op maat, apparatuur inbouwen en alles aansluiten op water, afvoer en stroom. Omdat we elektra, loodgieterswerk en tegelwerk zelf doen, kan de keuken in één doorlopende planning worden geplaatst.',
    ],
    faqs: [
      ['Moet mijn groepenkast vervangen worden?', 'Dat is vaak nodig als u weinig groepen of geen aardlekschakelaars heeft, of als u een inductiekookplaat of warmtepomp wilt aansluiten. We controleren uw huidige groepenkast en adviseren wat nodig is.'],
      ['Monteren jullie ook een keuken die ik elders heb gekocht?', 'Ja. We monteren keukens van elke leverancier, inclusief werkblad, apparatuur en de aansluitingen op water, afvoer en elektra.'],
      ['Werken jullie volgens NEN 1010?', 'Ja. Alle elektrische installaties leggen we aan volgens NEN 1010, en elke groep wordt na aanleg gemeten en getest.'],
    ],
  },
  {
    slug: 'dakwerk',
    name: 'Dakwerk & dakbedekking',
    short: 'dakwerk',
    icon: 'roof',
    card: 'Platte daken, dakkapellen en waterdichte aansluitingen die jaren meegaan.',
    tags: ['Plat dak', 'Dakkapel', 'Isolatie'],
    title: 'Dakdekker Rotterdam | Plat dak & dakkapel | Ideal House',
    desc: 'Dakdekker in Rotterdam voor platte daken, bitumen dakbedekking, dakisolatie, dakkapellen en lichtstraten. Lekkage? We sporen het op en repareren het. Gratis offerte.',
    h1: 'Dakwerk & dakbedekking in Rotterdam',
    intro: 'Een plat dak is pas zo goed als zijn detaillering. We werken met bitumineuze dakbedekking in twee lagen en besteden extra aandacht aan de opstanden, doorvoeren en aansluitingen. Daar ontstaan namelijk vrijwel alle lekkages.',
    hero: 'dakkapel-antraciet',
    gallery: ['dakkapel-nokverhoging', 'dakopbouw-gevelbekleding', 'plat-dak-lichtkoepel-uitbouw', 'gevel-dakopbouw-metselwerk', 'dakkapel-antraciet'],
    includes: [
      'Bitumineuze dakbedekking in twee lagen',
      'Dakisolatie volgens de huidige eisen',
      'Nieuwe dakranden, opstanden en trims',
      'Doorvoeren, hemelwaterafvoeren en noodoverlopen',
      'Dakkapellen en lichtstraten',
      'Lekkages opsporen en repareren',
    ],
    steps: [
      ['Dakinspectie', 'We beoordelen de bestaande opbouw, isolatie en het afschot.'],
      ['Ondergrond', 'Waar nodig vervangen we het dakbeschot en brengen we isolatie aan.'],
      ['Dakbedekking', 'Onderlaag en toplaag worden volledig gebrand of gekleefd.'],
      ['Details', 'Opstanden, doorvoeren en afvoeren worden waterdicht afgewerkt.'],
    ],
    about: [
      'Bij het vernieuwen van een plat dak is het hét moment om ook te isoleren. Een goed geïsoleerd dak scheelt merkbaar in uw energierekening en zorgt in de zomer voor een koelere bovenverdieping. We bouwen het dak op met isolatie volgens de huidige eisen en een dakbedekking die tegen het Nederlandse weer bestand is.',
      'Een dakkapel geeft uw zolder direct meer stahoogte, licht en bruikbare ruimte. We plaatsen dakkapellen met strakke afwerking in kunststof of plaatmateriaal, en sluiten ze waterdicht aan op het bestaande dak.',
    ],
    faqs: [
      ['Hoelang gaat een bitumen dak mee?', 'Een goed aangelegd bitumen dak in twee lagen gaat bij normaal onderhoud gemiddeld 20 tot 25 jaar mee. Regelmatig de afvoeren schoonhouden en de aansluitingen controleren helpt daarbij.'],
      ['Is een dakkapel vergunningvrij?', 'Een dakkapel op het achterdakvlak is onder voorwaarden vergunningvrij. Aan de voorkant of bij een monument is meestal een vergunning nodig. We bekijken dit samen met u tijdens de opname.'],
      ['Mijn dak lekt. Wat moet ik doen?', 'Bel of app ons, het liefst met een paar foto\'s van de plek. We komen kijken, sporen de oorzaak op en herstellen het. Vaak zit het probleem bij een opstand, doorvoer of afvoer.'],
    ],
  },
];

const GENERAL_FAQS = [
  ['Is een offerte echt gratis en vrijblijvend?', 'Ja. We komen langs, meten in en werken uw plan uit in een gespecificeerde offerte. Daar zijn geen kosten aan verbonden en u zit nergens aan vast. Pas als u akkoord geeft, plannen we het werk in.'],
  ['Hoelang duurt een badkamerrenovatie?', 'Een complete badkamer duurt gemiddeld 10 tot 15 werkdagen, afhankelijk van de grootte en of leidingen verlegd moeten worden. In de offerte noemen we een concrete doorlooptijd, zodat u weet waar u aan toe bent.'],
  ['Werken jullie met een vaste prijs of op nacalculatie?', 'Standaard werken we met een vaste aanneemsom op basis van de offerte. Komt er tijdens het werk iets onverwachts naar boven, bijvoorbeeld een verrotte vloerbalk, dan bespreken we dat eerst met u en leggen we het meerwerk schriftelijk vast voordat we verdergaan.'],
  ['Kan ik het materiaal zelf uitzoeken?', 'Zeker. Veel klanten kiezen zelf hun tegels en sanitair bij een showroom. We denken graag mee over wat praktisch werkt en kunnen ook het complete pakket voor u verzorgen.'],
  ['Heb ik een vergunning nodig voor een aanbouw?', 'Dat hangt af van de afmetingen en de locatie op het perceel. Veel uitbouwen aan de achterzijde zijn vergunningvrij. Tijdens de opname kijken we hiernaar en, als er wel een omgevingsvergunning nodig is, helpen we u met de aanvraag.'],
  ['In welke plaatsen zijn jullie actief?', 'We werken vanuit Rotterdam in de hele regio: Schiedam, Vlaardingen, Capelle aan den IJssel, Barendrecht, Ridderkerk, Spijkenisse, Delft, Den Haag, Dordrecht en omstreken. Twijfelt u of uw adres binnen ons werkgebied valt? Bel of app ons even.'],
  ['Blijft mijn huis bewoonbaar tijdens de verbouwing?', 'In de meeste gevallen wel. We dekken looppaden af, werken zoveel mogelijk stofarm en ruimen aan het eind van elke werkdag op. Bij een badkamerrenovatie is uw badkamer uiteraard tijdelijk niet te gebruiken; dat plannen we vooraf met u door.'],
  ['Krijg ik garantie op het werk?', 'Ja. Op ons uitgevoerde werk geeft Ideal House garantie; de exacte termijn en voorwaarden staan in de offerte en in onze algemene voorwaarden. Op materialen en apparatuur geldt daarnaast de fabrieksgarantie.'],
];

const STEPS = [
  ['talk', 'Kennismaking', 'U belt of appt ons met uw plan. We stellen een paar vragen en plannen een afspraak op locatie, meestal binnen een week.'],
  ['ruler', 'Opname en advies', 'We meten in, bekijken de bestaande situatie en denken mee. Soms blijkt een andere indeling handiger of goedkoper dan u dacht.'],
  ['file', 'Offerte op maat', 'U ontvangt een gespecificeerde offerte: per onderdeel wat we doen en wat het kost. Geen verrassingen achteraf.'],
  ['calendar', 'Planning', 'Na akkoord plannen we de startdatum en de doorlooptijd. U weet precies wanneer welke werkzaamheden plaatsvinden.'],
  ['wrench', 'Uitvoering', 'We werken door tot het klaar is. Aan het eind van elke dag ruimen we op, zodat u niet in een bouwput woont.'],
  ['key', 'Oplevering', 'We lopen het werk samen na. Punten die u opvallen lossen we op voordat we de sleutel teruggeven.'],
];

const WHY = [
  ['user', 'Eén aanspreekpunt', 'U belt met één persoon die het hele project overziet. Geen tussenpartijen die naar elkaar wijzen als er iets misgaat.'],
  ['euro', 'Vaste prijs vooraf', 'In de offerte staat per onderdeel wat het kost. Meerwerk bespreken we altijd eerst met u, voordat we het uitvoeren.'],
  ['eye', 'Oog voor detail', 'Strakke voegen, uitgelijnde tegels en nette aansluitingen. Het verschil zit in de afwerking die u pas van dichtbij ziet.'],
  ['calendar', 'Duidelijke planning', 'U weet vooraf wanneer we starten en hoelang het duurt. We werken door tot het af is en leveren schoon op.'],
];

const CATS = {
  aanbouw: 'Aanbouw & uitbouw',
  badkamer: 'Badkamer & toilet',
  dakwerk: 'Dakwerk & dakkapellen',
  afbouw: 'Afbouw & afwerking',
  uitvoering: 'In uitvoering',
};

module.exports = { BIZ, waLink, CITIES, DISTRICTS, SERVICES, GENERAL_FAQS, STEPS, WHY, CATS };
